version: 2.1
orbs:
  ruby: circleci/ruby@1.1.4

jobs:
  test:
    docker:
      - image: cimg/ruby:2.7.3-node
    steps:
      - ruby/install-deps:
          bundler-version: 1.17.2
      - ruby/rspec-test

workflows:
  build_and_test:
    jobs:
      - test